apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kubernetes-csi-addons
  name: csi-addons-csiaddons-networkfenceclass-editor-role
rules:
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - networkfenceclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - networkfenceclasses/status
  verbs:
  - get
