apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odf-operator1
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
