apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: csi-addons
spec:
  namespace: nigoyal
  serviceAccount:
    name: installer
  source:
    sourceType: Catalog
    catalog:
      packageName: csi-addons
      version: 0.14.0
